// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var Conntrack = NewRuntimeAsset("conntrack.c", "baa328f6f4997052e451c434b585f62193f9493f808f0564a6a45c6846a7635e")
