// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "14e437288075dfb886641eba398c97fd6298e13c953fd2a13924dd6b3d08be4d")
