// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "88fb7e3bca132a3180ea65b2b4884284142f58cf36ae124da8db5c1d424a6c17")
