// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "8309f0e1c76c004cb55dd444e96785c41df9fdf9470e9c15895f11346f124da4")
